### ISSUE TITLE
Insecure /tmp usage with static path /tmp/scalemate.log (use mktemp instead or not shared /tmp like ~/tmp)

### ISSUE THREAD

**Issue by emanuelb** [eladnava/scalemate#1]
Static path /tmp/scalemate.log is used in:
https://github.com/eladnava/scalemate/blob/c9ae678847a0df675ffd1b6ead526e0c82e07849/README.md#L82
https://github.com/eladnava/scalemate/blob/c9ae678847a0df675ffd1b6ead526e0c82e07849/README.md#L88

thus vulnerable to malicious usage from other users/processes which will create it in advance with link to another location.

Using mktemp to generate the tmp file is better, also creating a temporary directory with `mktemp -d` and working with static names in it is ok (or creating temp dir for each usage by `mktemp -d --suffix='-some-related-suffix'`), also not using shared `/tmp/` but another location like `/home/user/tmp/` or `~/tmp/` is also a fix.

Using static names in /tmp/ shared folder is wrong for several reasons including security, you can read more about it:
https://stackoverflow.com/questions/11636790/why-do-we-need-mktemp

**Comment by eladnava** [comment]
Hi @emanuelb,
Thanks for your issue report. A PR with a fix will be appreciated. 👍

**Comment by eladnava** [comment]
Fixed in https://github.com/eladnava/scalemate/commit/b3a7c2b925f2e74fb181c9d5cb100948ed6ad34d.
